spring.application.name=cgaf

server.servlet.context-path=/api/v1

# Executa scripts SQL automaticamente na inicializacao (schema.sql, data.sql)
spring.sql.init.mode=always

# Define o nivel de log do Hibernate como ERROR
logging.level.org.hibernate=ERROR

spring.datasource.url=jdbc:postgresql://localhost:5432/cgaf_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Define como o Hibernate trata o schema do banco
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
# Executar scripts depois do Hibernate criar as tabelas
spring.jpa.defer-datasource-initialization=true
# Mostra no console os SQLs executados pelo Hibernate
#spring.jpa.show-sql=true
# Facilita leitura quando show-sql esta ativo
#spring.jpa.properties.hibernate.format_sql=true

api.security.token.secret=${JWT_SECRET:cgaf-key-super-secreta-na-pegada-32-bytes}
app.default-password=cgaf@ucsal